#!/bin/bash
# PostToolUse hook (Write / Edit / MultiEdit): auto-maintain a per-project
# docs/INDEX.md and nudge when a doc lands outside docs/.
#
# me2resh/apexyard#753.
#
# ADVISORY ONLY — exit 0 always, never blocks a tool call. Same shape as
# check-upstream-drift.sh / detect-role-trigger.sh.
#
# Gated OFF by default: does nothing unless `docs_index.enabled` is true in
# .claude/project-config.json. When enabled, a *.md / *.html write under
# <projects_dir>/<name>/ triggers two effects:
#
#   1. (Re)generate <project>/docs/<index_filename> — a grouped, date-aware
#      table-of-contents of the docs under docs/ (relative path, title from the
#      first heading, and created + last-modified dates from git history).
#   2. Warn (non-blocking, stderr) when the written doc is under the project but
#      OUTSIDE docs/, suggesting docs/ for admin-dashboard visibility.
#
# Silent exit paths (no output, exit 0):
#   - not enabled in config (the default)
#   - jq unavailable / no defaults file (not an apexyard fork)
#   - no file_path in the payload, or the file is not *.md / *.html
#   - the file is not under <projects_dir>/<name>/
#   - the written file IS the index file (no self-recursion)
#
# The index is written with a plain shell redirect (not the Write tool), so it
# does not re-trigger this PostToolUse hook — no recursion.
#
# Runtime: a few ms when disabled (one cached config read); on a doc write with
# the feature enabled, O(number of docs) git calls to gather dates.

set -u

INPUT=$(cat)

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=/dev/null
. "$HOOK_DIR/_lib-read-config.sh" 2>/dev/null || exit 0
# shellcheck source=/dev/null
. "$HOOK_DIR/_lib-portfolio-paths.sh" 2>/dev/null || exit 0

command -v jq >/dev/null 2>&1 || exit 0

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# _doc_title <file> — a human title: first markdown heading, else <title>/<h1>
# for HTML, else the basename.
_doc_title() {
  local f="$1" t=""
  case "$f" in
    *.md)
      t=$(grep -m1 -E '^#{1,6}[[:space:]]+' "$f" 2>/dev/null \
        | sed -E 's/^#{1,6}[[:space:]]+//; s/[[:space:]]+$//')
      ;;
    *.html|*.htm)
      t=$(grep -m1 -ioE '<title>[^<]*</title>' "$f" 2>/dev/null | sed -E 's/<[^>]+>//g')
      [ -z "$t" ] && t=$(grep -m1 -ioE '<h1[^>]*>[^<]*</h1>' "$f" 2>/dev/null | sed -E 's/<[^>]+>//g')
      t=$(printf '%s' "$t" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
      ;;
  esac
  [ -z "$t" ] && t="$(basename "$f")"
  printf '%s' "$t"
}

# _md_cell <text> — make an untrusted string safe inside a markdown table cell
# that a downstream consumer (the admin dashboard) may render as HTML: escape
# the HTML-significant chars and the table delimiter. '&' MUST be first so the
# entities we introduce below aren't re-escaped (me2resh/apexyard#768 review).
_md_cell() {
  printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/|/\\|/g'
}

# _md_link <text> — as _md_cell, plus neutralise the markdown-link structural
# chars so a crafted filename can't break out of `[text](url)` into an injected
# link / HTML (e.g. a doc literally named `x](javascript:alert(1)).md`).
_md_link() {
  _md_cell "$1" | sed -e 's/\[/%5B/g' -e 's/\]/%5D/g' -e 's/(/%28/g' -e 's/)/%29/g'
}

# _doc_dates <file> — "created<TAB>modified" from git history (ISO dates).
# Both fall back to "—" when the file is untracked / not in a git repo.
_doc_dates() {
  local f="$1" dir base created modified
  dir="$(dirname "$f")"; base="$(basename "$f")"
  created=$(git -C "$dir" log --diff-filter=A --follow --format=%as -- "$base" 2>/dev/null | tail -1)
  modified=$(git -C "$dir" log -1 --format=%as -- "$base" 2>/dev/null)
  [ -z "$created" ] && created="—"
  [ -z "$modified" ] && modified="—"
  printf '%s\t%s' "$created" "$modified"
}

# _generate_index <docs_dir> <index_file> <project_name>
# Rewrites <index_file> as a grouped, date-aware TOC of docs under <docs_dir>.
_generate_index() {
  local ddir="$1" ifile="$2" pname="$3"
  local iname tmp files groups g rel rel_esc abs title dates created modified
  iname="$(basename "$ifile")"

  tmp=$(mktemp) || return 0
  {
    printf '# Docs Index — %s\n\n' "$(_md_cell "$pname")"
    printf '<!-- AUTO-GENERATED by .claude/hooks/maintain-docs-index.sh (me2resh/apexyard#753). Do not edit by hand — it is rewritten whenever a doc under this project changes. -->\n\n'
  } > "$tmp"

  # All docs under docs/, relative to docs/, excluding the index itself. Stable sort.
  files=$(cd "$ddir" && find . -type f \( -name '*.md' -o -name '*.html' -o -name '*.htm' \) 2>/dev/null \
    | sed 's|^\./||' | grep -v -x -F "$iname" | LC_ALL=C sort)

  if [ -z "$files" ]; then
    printf '_No docs yet._\n' >> "$tmp"
    mv "$tmp" "$ifile"
    return 0
  fi

  # Group by top-level subdir under docs/; root-level files go under "General".
  groups=$(printf '%s\n' "$files" | awk -F/ '{ if (NF>1) print $1; else print "General" }' | LC_ALL=C sort -u)

  while IFS= read -r g; do
    [ -n "$g" ] || continue
    printf '## %s\n\n' "$(_md_cell "$g")" >> "$tmp"
    printf '| Doc | Title | Created | Modified |\n|-----|-------|---------|----------|\n' >> "$tmp"
    while IFS= read -r rel; do
      [ -n "$rel" ] || continue
      case "$rel" in
        */*) [ "${rel%%/*}" = "$g" ] || continue ;;
        *)   [ "$g" = "General" ] || continue ;;
      esac
      abs="$ddir/$rel"
      title=$(_doc_title "$abs")
      dates=$(_doc_dates "$abs")
      created="${dates%%$'\t'*}"; modified="${dates##*$'\t'}"
      # Escape untrusted title + path so a hostile filename / heading can't inject
      # HTML or break the markdown table/link when the dashboard renders INDEX.md.
      title=$(_md_cell "$title")
      rel_esc=$(_md_link "$rel")
      printf '| [%s](%s) | %s | %s | %s |\n' "$rel_esc" "$rel_esc" "$title" "$created" "$modified" >> "$tmp"
    done <<EOF
$files
EOF
    printf '\n' >> "$tmp"
  done <<EOF
$groups
EOF

  mv "$tmp" "$ifile"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

# Config gate (default OFF).
ENABLED=$(config_get_or '.docs_index.enabled' 'false')
[ "$ENABLED" = "true" ] || exit 0

INDEX_NAME=$(config_get_or '.docs_index.index_filename' 'INDEX.md')

# The changed file.
FILE_PATH=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null)
[ -n "$FILE_PATH" ] || exit 0

case "$FILE_PATH" in
  *.md|*.html|*.htm) ;;
  *) exit 0 ;;
esac

# Absolutise.
case "$FILE_PATH" in
  /*) ABS_FILE="$FILE_PATH" ;;
  *)  ABS_FILE="$(pwd)/$FILE_PATH" ;;
esac

# Must be under <projects_dir>/<name>/.
PROJECTS_DIR=$(portfolio_projects_dir 2>/dev/null)
[ -n "$PROJECTS_DIR" ] || exit 0
[ -d "$PROJECTS_DIR" ] && PROJECTS_DIR="$(cd "$PROJECTS_DIR" && pwd -P)"

case "$ABS_FILE" in
  "$PROJECTS_DIR"/*) ;;
  *) exit 0 ;;
esac

REL="${ABS_FILE#"$PROJECTS_DIR"/}"
PROJECT_NAME="${REL%%/*}"
[ -n "$PROJECT_NAME" ] || exit 0
[ "$PROJECT_NAME" = "$REL" ] && exit 0   # file sat directly in projects_dir, no project

# ABS_FILE is not path-normalised, and the containment glob above matches '/',
# so a file_path like "<projects_dir>/../docs/x.md" passes the guard textually
# and yields PROJECT_NAME=".." — which would make the write target escape
# projects/<name>/docs/ (me2resh/apexyard#768 security review). Every downstream
# path (DOCS_DIR, INDEX_FILE, the find root) is rebuilt from PROJECT_NAME, so
# rejecting a traversal/degenerate name here contains both the write and read.
case "$PROJECT_NAME" in
  ''|.|..|*/*) exit 0 ;;
esac

PROJECT_ROOT="$PROJECTS_DIR/$PROJECT_NAME"
DOCS_DIR="$PROJECT_ROOT/docs"
INDEX_FILE="$DOCS_DIR/$INDEX_NAME"

# Never recurse on our own index write.
[ "$ABS_FILE" = "$INDEX_FILE" ] && exit 0

# Path within the project (after the project name).
IN_PROJECT="${REL#"$PROJECT_NAME"/}"

# Nudge when the doc is under the project but outside docs/.
case "$IN_PROJECT" in
  docs/*) ;;
  *)
    printf '\n📄 docs-index (#753): projects/%s/%s was written OUTSIDE docs/.\n' "$PROJECT_NAME" "$IN_PROJECT" >&2
    printf '   The admin dashboard surfaces only projects/%s/docs/ — consider moving it there for visibility.\n\n' "$PROJECT_NAME" >&2
    ;;
esac

# Regenerate the index (only when docs/ exists).
[ -d "$DOCS_DIR" ] || exit 0
_generate_index "$DOCS_DIR" "$INDEX_FILE" "$PROJECT_NAME"
exit 0
