/**
 * derive-gates-core.ts — the harness-agnostic half of "parse
 * `.claude/settings.json`'s `PreToolUse` wiring into a gate table."
 *
 * WHY THIS EXISTS (#840 C5 — the pi/opencode convergence)
 * -----------------------------------------------------------
 * `harness-adapters/opencode/src/derive-gates.ts` (AgDR-0092) proved the
 * settings.json-derived pattern is strictly better than a hand-maintained
 * gate table (AgDR-0082's original `DEFAULT_GATES` in the pi adapter):
 * zero drift by construction, a new hook wired in `.claude/settings.json`
 * is picked up automatically. AgDR-0092 itself named porting pi to the
 * same pattern as the intended follow-up, deliberately deferred out of
 * that PR's scope. This module is that follow-up's shared foundation.
 *
 * The regex extraction (`.claude/hooks/*.sh` path, `Bash(<glob>)`
 * predicate), the glob-to-RegExp conversion, and the settings.json
 * matcher-group -> `GateDefinition` collapsing logic are 100% IDENTICAL
 * between pi and opencode — none of it references a runtime's own tool
 * vocabulary. What differs between the two runtimes is everything
 * DOWNSTREAM of that: which runtime tool id a Claude Code matcher token
 * maps to (opencode has a `glob` tool; pi does not — pi's closest analog
 * is `find`), and what field name each runtime's tool call event uses for
 * its target (opencode: `filePath`; pi: `path`). This module deliberately
 * stops BEFORE that translation — gates here are keyed by the RAW Claude
 * Code matcher token (`"Bash"`, `"Edit"`, `"Write"`, `"MultiEdit"`,
 * `"Read"`, `"Glob"`, `"Grep"`), not by any runtime's own tool id. Each
 * per-runtime `derive-gates.ts` (opencode's, pi's) does its own
 * matcher-to-tool translation on top of this core.
 *
 * This is intentionally NOT a full "shared adapter" — `buildToolInput`
 * (constructing the runtime-shaped tool-call arguments into the
 * Claude-Code-shaped stdin payload) and the runtime-to-Claude tool-name
 * reverse mapping stay per-adapter, because those genuinely differ by
 * runtime and guessing a shared shape for them would be worse than two
 * short, explicit, independently-reviewable functions (see each
 * adapter's own `derive-gates.ts` header comment).
 */

/** Minimal shape of `.claude/settings.json` this module reads — a structural subset, not the full schema. */
export interface RawHookEntry {
  type?: string;
  command?: string;
  if?: string;
}
export interface RawMatcherGroup {
  matcher?: string;
  hooks?: RawHookEntry[];
}
export interface RawSettings {
  hooks?: {
    PreToolUse?: RawMatcherGroup[];
  };
}

/**
 * One wiring row: "this hook fires for this RAW CLAUDE CODE MATCHER TOKEN
 * (e.g. `"Bash"`, `"Edit"`, `"MultiEdit"`), optionally only when the Bash
 * command matches this glob." Mirrors one `{matcher, hooks[].if}`
 * combination from `.claude/settings.json`, one matcher token at a time
 * (a `"Edit|Write|MultiEdit"` matcher group produces three wires, one per
 * token — the per-runtime adapter decides how those three tokens map onto
 * its own tool ids).
 *
 * `commandGlob: null` means the hook fires unconditionally for this
 * matcher token — either because the matcher's group carried no `if`
 * predicate at all, or the row's `if` value didn't parse as a
 * `Bash(<glob>)` predicate.
 */
export interface GateWire {
  /** Raw Claude Code matcher token this wire applies to (e.g. "Bash", "Edit", "Read"). */
  claudeMatcher: string;
  /** Bash-command glob (from Claude Code's `if: "Bash(<glob>)"`), or null. */
  commandGlob: string | null;
}

/**
 * A single `.claude/hooks/*.sh` gate, reconstructed from one or more
 * `.claude/settings.json` `PreToolUse` entries that all point at the same
 * hook script.
 */
export interface GateDefinition {
  /** Human-readable name (the hook's basename, no extension), used in block reasons. */
  name: string;
  /** Path to the hook script, relative to the ops root — e.g. ".claude/hooks/block-unreviewed-merge.sh". */
  hookRelativePath: string;
  /** Every (claudeMatcher, commandGlob) combination this gate is wired to. */
  wires: GateWire[];
}

/**
 * Extracts the `.claude/hooks/<file>.sh` path from a settings.json hook
 * `command` string. The command is the ops-root-pin bash wrapper (see
 * `pin-ops-root.sh` / `_lib-ops-root.sh`) that ultimately execs
 * `"$r/.claude/hooks/<file>.sh"` — this is a regex extraction of that
 * trailing path, not a full shell parse, matching the extraction
 * discipline `_lib-extract-pr.sh` already uses elsewhere in this framework
 * ("regex-only extraction, sufficient for the shapes these commands
 * actually emit" — the shape here is generated by this repo's own
 * `settings.json`, not attacker-controlled input).
 */
export function extractHookRelativePath(command: string | undefined): string | undefined {
  if (!command) return undefined;
  const m = command.match(/\.claude\/hooks\/([\w.-]+\.sh)\b/);
  return m ? `.claude/hooks/${m[1]}` : undefined;
}

/** Extracts the glob from a Claude Code `if: "Bash(<glob>)"` predicate string, or undefined if it doesn't match that shape. */
export function extractCommandGlob(ifPredicate: string | undefined): string | undefined {
  if (!ifPredicate) return undefined;
  const m = ifPredicate.match(/^Bash\((.*)\)$/);
  return m ? m[1] : undefined;
}

function hookNameFromPath(hookRelativePath: string): string {
  const base = hookRelativePath.split("/").pop() ?? hookRelativePath;
  return base.replace(/\.sh$/, "");
}

/**
 * Derives the full gate table from a parsed `.claude/settings.json`,
 * keyed by RAW Claude Code matcher tokens — no runtime tool-id
 * translation happens here (see this file's header comment for why).
 *
 * Every `PreToolUse` entry whose command execs a `.claude/hooks/*.sh`
 * script becomes (or is folded into) a `GateDefinition` — grouped by hook
 * path because the same hook is commonly wired multiple times (once per
 * Bash-command-glob it cares about, e.g. `block-unreviewed-merge.sh` is
 * wired 5 times: `gh pr merge *`, `gh api *`, `glab mr merge *`,
 * `glab api *`, `tracker_pr_merge *` — the multi-tracker merge-shape
 * coverage from #47/#759).
 *
 * Entries whose `command` doesn't reference a `.claude/hooks/*.sh` file are
 * skipped — none exist in this framework's own wiring today, but a future
 * adopter's custom hook shape shouldn't crash gate derivation.
 */
export function deriveGatesFromSettings(settings: RawSettings): GateDefinition[] {
  const byHook = new Map<string, GateDefinition>();
  const preToolUse = settings.hooks?.PreToolUse ?? [];

  for (const group of preToolUse) {
    const claudeMatchers = (group.matcher ?? "")
      .split("|")
      .map((s) => s.trim())
      .filter(Boolean);
    if (claudeMatchers.length === 0) continue; // no matcher at all (e.g. a SessionStart-shaped group) — not a PreToolUse gate

    for (const entry of group.hooks ?? []) {
      if (entry.type && entry.type !== "command") continue; // not a shell command hook
      const hookRelativePath = extractHookRelativePath(entry.command);
      if (!hookRelativePath) continue;

      let gate = byHook.get(hookRelativePath);
      if (!gate) {
        gate = { name: hookNameFromPath(hookRelativePath), hookRelativePath, wires: [] };
        byHook.set(hookRelativePath, gate);
      }

      // `if` predicates in this framework's wiring only ever gate the Bash
      // matcher (command-shape matching) — Edit/Write/Read/Glob/Grep rows
      // carry no `if` field. Applying the glob only to the "Bash" matcher
      // and treating every other matcher as unconditional matches that
      // reality without needing to special-case matcher names here.
      const commandGlob = extractCommandGlob(entry.if) ?? null;
      for (const claudeMatcher of claudeMatchers) {
        gate.wires.push({ claudeMatcher, commandGlob: claudeMatcher === "Bash" ? commandGlob : null });
      }
    }
  }

  return Array.from(byHook.values());
}

/** Converts a Claude Code `if: "Bash(<glob>)"` glob (shell-style `*` wildcard) into an anchored RegExp. */
export function globToRegExp(glob: string): RegExp {
  const escaped = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*");
  return new RegExp(`^${escaped}$`);
}

/**
 * True if `gate` has a wire for `claudeMatcher` that matches the given
 * (optional — only Bash calls carry one) `command` string. A wire with no
 * glob (`commandGlob === null`) always matches; otherwise it matches if
 * `command` matches its glob (mirrors Claude Code's own PreToolUse
 * semantics: multiple `if` predicates on the same hook are alternatives,
 * not conjunctions).
 */
export function gateMatchesClaudeMatcher(gate: GateDefinition, claudeMatcher: string, command: string | undefined): boolean {
  for (const wire of gate.wires) {
    if (wire.claudeMatcher !== claudeMatcher) continue;
    if (wire.commandGlob === null) return true;
    if (typeof command === "string" && globToRegExp(wire.commandGlob).test(command)) return true;
  }
  return false;
}
